feat: add all required endpoints
rohitxsh/ensembl_lakehouse pull request #9
Opened 2022-07-20 13:01 UTC by rohitxsh

2022-07-20 13:31 UTC, andrewyatz approved these changes
As a first pass this looks good to me

2022-07-20 14:38 UTC, marcoooo requested changes

2022-07-20 14:38 UTC, marcoooo commented on main.py
> +@app.get("/api/v1")
You'd better think of your app as "behind a proxy" e.g. the relative uri is never mentioned in your code, so the day you switch to /api/v2 your routes definition don't change. More info here: https://fastapi.tiangolo.com/advanced/behind-a-proxy/
Therefore your route must be defined as "relative", this one should ten become
```suggestion
@app.get("/")
```

2022-07-20 14:38 UTC, marcoooo commented on main.py
> +@app.get("/api/v1/data")
Following first comment this one should become
```suggestion
@app.get("/data")
```

2022-07-20 14:38 UTC, marcoooo commented on main.py
> +@app.get("/api/v1/{data}/columns")
Same comment, and I would ass that {data} could be misleading with previous route, if it's a `data_type` then change the name for this. 
```suggestion
@app.get("/{data_type}/columns")
```

2022-07-20 14:38 UTC, marcoooo commented on main.py
> +@app.get("/api/v1/query/{queryId}/status")
```suggestion
@app.get("/query/{queryId}/status")
```

2022-07-20 14:38 UTC, marcoooo commented on main.py
> +@app.get("/api/v1/query/{data}/{species}")
```suggestion
@app.get("/query/{data_type}/{species}")
```

2022-07-22 10:40 UTC, marcoooo approved these changes

2022-07-22 10:43 UTC, bilalebi approved these changes

2022-07-25 21:25 UTC, rohitxsh commented
Changes:
Have split the endpoint for status and preview
Update query endpoint as per content-type content-type: application/hal+json (https://tools.ietf.org/id/draft-kelly-json-hal-01.html)
Preview endpoint now only return 25 rows excluding header
Sort the query string to generate base64 which is used as cache key for redis
Now caching /data and {data_type/columns too
Query endpoint now accepts custom fields too as comma separated values
Redis host and port can be updated by setting env. variable, details added in readme
Added dockerfile, details added in readme
Moved the code to a module
Added logging, added a middleware which logs details like url path, time taken, status code
Added new header X-Correlation-ID which can be used to search for error in logs
Customised the doc generated by FastAPI which can now be used a full fledged documentation for the API endpoints

2022-07-26 09:39 UTC, andrewyatz approved these changes

2022-07-27 11:08 UTC, merged